<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <None Remove="Configurations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduOS.Core\EduOS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Validators\Admission\" />
    <Folder Include="Validators\Finance\" />
    <Folder Include="Validators\Payroll\" />
    <Folder Include="Validators\Student\" />
    <Folder Include="Validators\Teacher\" />
  </ItemGroup>

</Project>
