<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <None Remove="Configurations\**" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="EPPlus" Version="8.6.3" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Hangfire" Version="1.8.24" />
	<PackageReference Include="MailKit" Version="4.17.0" />
	<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduOS.Core\EduOS.Core.csproj" />
    <ProjectReference Include="..\EduOS.Persistence\EduOS.Persistence.csproj" />
  </ItemGroup>

</Project>
