using EduOS.Core.Common;
using EduOS.Core.DTOs.Admission;
using EduOS.Core.Entities.Academic;
using EduOS.Core.Entities.Admission;
using EduOS.Core.Entities.Files;
using EduOS.Core.Entities.SaaS;
using EduOS.Core.Enums;
using EduOS.Core.Enums.Domain;
using EduOS.Core.Interfaces;
using EduOS.Core.Interfaces.IRepositories;
using EduOS.Core.Interfaces.IServices;
using EduOS.Service.Helpers.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Security.Cryptography;
using System.Transactions;

namespace EduOS.Service.Services.Admission;

public sealed class AdmissionIntakeService : IAdmissionIntakeService
{
    private readonly IGenericRepository<AdmissionIntakeForm> _forms;
    private readonly IGenericRepository<AdmissionFormField> _fields;
    private readonly IGenericRepository<AdmissionApplicant> _applicants;
    private readonly IGenericRepository<AdmissionApplicantDocument> _documents;
    private readonly IGenericRepository<FileAsset> _fileAssets;
    private readonly IGenericRepository<AcademicYear> _years;
    private readonly IGenericRepository<AcademicTerm> _terms;
    private readonly IGenericRepository<Campus> _campuses;
    private readonly IGenericRepository<AcademicLevel> _levels;
    private readonly IUnitOfWork _uow;
    private readonly ICurrentUserService _user;
    private readonly IFileUploadService _storage;
    private readonly TimeProvider _clock;
    private readonly ILogger<AdmissionIntakeService> _logger;

    public AdmissionIntakeService(IGenericRepository<AdmissionIntakeForm> forms,
        IGenericRepository<AdmissionFormField> fields,
        IGenericRepository<AdmissionApplicant> applicants,
        IGenericRepository<AdmissionApplicantDocument> documents,
        IGenericRepository<FileAsset> fileAssets,
        IGenericRepository<AcademicYear> years, IGenericRepository<AcademicTerm> terms,
        IGenericRepository<Campus> campuses, IGenericRepository<AcademicLevel> levels,
        IUnitOfWork unitOfWork, ICurrentUserService currentUser, IFileUploadService storage,
        TimeProvider clock, ILogger<AdmissionIntakeService> logger)
    {
        _forms = forms; _fields = fields; _applicants = applicants;
        _documents = documents; _fileAssets = fileAssets; _years = years;
        _terms = terms; _campuses = campuses; _levels = levels;
        _uow = unitOfWork; _user = currentUser; _storage = storage;
        _clock = clock; _logger = logger;
    }

    public async Task<ApiResponse<IReadOnlyList<AdmissionIntakeFormDto>>> GetFormsAsync(CancellationToken ct = default)
    {
        if (!CanManage()) return Denied<IReadOnlyList<AdmissionIntakeFormDto>>();
        var tenant = _user.TenantId;
        var forms = await _forms.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant)
            .OrderByDescending(x => x.CreatedAt).ThenByDescending(x => x.Id).Take(200).ToListAsync(ct);
        var ids = forms.Select(x => x.Id).ToArray();
        var fields = await _fields.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant &&
            ids.Contains(x.AdmissionIntakeFormId) && x.IsActive)
            .OrderBy(x => x.DisplayOrder).ThenBy(x => x.Id).ToListAsync(ct);
        var groups = fields.GroupBy(x => x.AdmissionIntakeFormId)
            .ToDictionary(x => x.Key, x => x.Select(MapField).ToArray());
        IReadOnlyList<AdmissionIntakeFormDto> result = forms.Select(x =>
            MapForm(x, groups.GetValueOrDefault(x.Id) ?? Array.Empty<AdmissionFormFieldDto>())).ToList();
        return ApiResponse<IReadOnlyList<AdmissionIntakeFormDto>>.SuccessResponse(result);
    }

    public Task<ApiResponse<AdmissionIntakeFormDto>> CreateFormAsync(CreateAdmissionIntakeFormDto request,
        CancellationToken ct = default)
    {
        if (!CanManage()) return Task.FromResult(Denied<AdmissionIntakeFormDto>());
        var error = ValidateInput(request);
        if (request == null || request.ClientRequestId == Guid.Empty || error != null || request.Fields.Any(x => x.Id > 0))
            return Task.FromResult(Error<AdmissionIntakeFormDto>(error ?? "Client request ID is required and field IDs must be generated by the server."));
        return ExecuteWriteAsync("create admission form", async () =>
        {
            var tenant = _user.TenantId;
            var code = request.Code.Trim().ToUpperInvariant();
            var existing = await _forms.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
                x.TenantId == tenant && x.Code == code, ct);
            if (existing != null)
                return Error<AdmissionIntakeFormDto>("Admission form code already exists; choose a unique code.", 409);
            var level = await ValidateReferencesAsync(request, ct);
            if (level == null) return Error<AdmissionIntakeFormDto>("Invalid year, campus, term or academic level.", 409);
            var now = _clock.GetUtcNow().UtcDateTime;
            var form = new AdmissionIntakeForm
            {
                TenantId = tenant, PublicId = Guid.NewGuid(), Code = code, Title = request.Title.Trim(),
                CampusId = request.CampusId, AcademicYearId = request.AcademicYearId,
                AcademicTermId = request.AcademicTermId, AcademicProgramId = level.AcademicProgramId,
                AcademicLevelId = level.Id, VersionNo = 1,
                OpensAt = AdmissionIntakeRules.Utc(request.OpensAtUtc),
                ClosesAt = AdmissionIntakeRules.Utc(request.ClosesAtUtc),
                ApplicationFee = request.ApplicationFee, CurrencyCode = request.Currency.Trim().ToUpperInvariant(),
                State = AdmissionFormState.Draft, CreatedAt = now, CreatedBy = _user.UserId
            };
            await _forms.AddAsync(form);
            await _uow.SaveChangesAsync(ct);
            foreach (var field in request.Fields)
                await _fields.AddAsync(BuildField(form.Id, field, now));
            await _uow.SaveChangesAsync(ct);
            var savedFields = await _fields.GetQueryable().AsNoTracking().Where(x =>
                x.TenantId == tenant && x.AdmissionIntakeFormId == form.Id && x.IsActive)
                .OrderBy(x => x.DisplayOrder).ToListAsync(ct);
            return Created(MapForm(form, savedFields.Select(MapField).ToArray()), "Admission form created as draft.");
        });
    }

    public Task<ApiResponse<AdmissionIntakeFormDto>> UpdateFormAsync(long id, UpdateAdmissionIntakeFormDto request,
        CancellationToken ct = default)
    {
        if (!CanManage()) return Task.FromResult(Denied<AdmissionIntakeFormDto>());
        var error = ValidateInput(request);
        if (id <= 0 || request == null || error != null || !TryVersion(request.RowVersion, out var version))
            return Task.FromResult(Error<AdmissionIntakeFormDto>(error ?? "Valid form and row version are required."));
        return ExecuteWriteAsync("update admission form", async () =>
        {
            var tenant = _user.TenantId;
            var form = await _forms.GetQueryable().FirstOrDefaultAsync(x => x.TenantId == tenant && x.Id == id, ct);
            if (form == null) return Error<AdmissionIntakeFormDto>("Admission form not found.", 404);
            if (form.State != AdmissionFormState.Draft)
                return Error<AdmissionIntakeFormDto>("Only a draft admission form can be edited.", 409);
            if (!VersionsMatch(form.RowVersion, version)) return Stale<AdmissionIntakeFormDto>();
            var level = await ValidateReferencesAsync(request, ct);
            if (level == null) return Error<AdmissionIntakeFormDto>("Invalid year, campus, term or academic level.", 409);
            var code = request.Code.Trim().ToUpperInvariant();
            if (await _forms.GetQueryable().AsNoTracking().AnyAsync(x =>
                x.TenantId == tenant && x.Id != id && x.Code == code, ct))
                return Error<AdmissionIntakeFormDto>("Admission form code already exists.", 409);
            var now = _clock.GetUtcNow().UtcDateTime;
            form.Code = code; form.Title = request.Title.Trim();
            form.CampusId = request.CampusId; form.AcademicYearId = request.AcademicYearId;
            form.AcademicTermId = request.AcademicTermId; form.AcademicProgramId = level.AcademicProgramId;
            form.AcademicLevelId = level.Id;
            form.OpensAt = AdmissionIntakeRules.Utc(request.OpensAtUtc);
            form.ClosesAt = AdmissionIntakeRules.Utc(request.ClosesAtUtc);
            form.ApplicationFee = request.ApplicationFee;
            form.CurrencyCode = request.Currency.Trim().ToUpperInvariant();
            form.UpdatedAt = now; form.UpdatedBy = _user.UserId;
            var previous = await _fields.GetQueryable().Where(x => x.TenantId == tenant &&
                x.AdmissionIntakeFormId == id).ToListAsync(ct);
            var incoming = request.Fields.ToDictionary(x => x.FieldKey.Trim(), StringComparer.OrdinalIgnoreCase);
            foreach (var old in previous)
            {
                if (!incoming.TryGetValue(old.FieldKey, out var updated))
                {
                    old.IsActive = false; old.UpdatedAt = now; old.UpdatedBy = _user.UserId;
                    continue;
                }
                if (updated.Id > 0 && updated.Id != old.Id)
                    return Error<AdmissionIntakeFormDto>("Field ID does not match its existing key.", 409);
                if (!string.IsNullOrWhiteSpace(updated.RowVersion) &&
                    (!TryVersion(updated.RowVersion, out var fieldVersion) || !VersionsMatch(old.RowVersion, fieldVersion)))
                    return Stale<AdmissionIntakeFormDto>();
                ApplyField(old, updated);
                old.UpdatedAt = now; old.UpdatedBy = _user.UserId;
                incoming.Remove(old.FieldKey);
            }
            if (incoming.Values.Any(x => x.Id > 0))
                return Error<AdmissionIntakeFormDto>("Unknown field ID cannot be added to a form.", 409);
            foreach (var added in incoming.Values)
                await _fields.AddAsync(BuildField(id, added, now));
            await _uow.SaveChangesAsync(ct);
            var savedFields = await _fields.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant &&
                x.AdmissionIntakeFormId == id && x.IsActive).OrderBy(x => x.DisplayOrder).ToListAsync(ct);
            return ApiResponse<AdmissionIntakeFormDto>.SuccessResponse(
                MapForm(form, savedFields.Select(MapField).ToArray()), "Admission form updated.");
        });
    }

    public Task<ApiResponse<AdmissionIntakeFormDto>> PublishFormAsync(long id, AdmissionRowVersionDto request,
        CancellationToken ct = default) =>
        TransitionAsync(id, request, AdmissionFormState.Draft, AdmissionFormState.Published, ct);

    public Task<ApiResponse<AdmissionIntakeFormDto>> CloseFormAsync(long id, AdmissionRowVersionDto request,
        CancellationToken ct = default) =>
        TransitionAsync(id, request, AdmissionFormState.Published, AdmissionFormState.Closed, ct);

    private Task<ApiResponse<AdmissionIntakeFormDto>> TransitionAsync(long id, AdmissionRowVersionDto request,
        AdmissionFormState from, AdmissionFormState to, CancellationToken ct)
    {
        if (!CanManage()) return Task.FromResult(Denied<AdmissionIntakeFormDto>());
        if (id <= 0 || request == null || !TryVersion(request.RowVersion, out var version))
            return Task.FromResult(Error<AdmissionIntakeFormDto>("Form ID and row version are required."));
        return ExecuteWriteAsync("change admission form state", async () =>
        {
            var tenant = _user.TenantId;
            var form = await _forms.GetQueryable().FirstOrDefaultAsync(x => x.TenantId == tenant && x.Id == id, ct);
            if (form == null) return Error<AdmissionIntakeFormDto>("Admission form not found.", 404);
            if (!VersionsMatch(form.RowVersion, version)) return Stale<AdmissionIntakeFormDto>();
            if (form.State != from)
                return Error<AdmissionIntakeFormDto>("Admission form is not in a valid state for this transition.", 409);
            if (to == AdmissionFormState.Published &&
                (!form.OpensAt.HasValue || !form.ClosesAt.HasValue || form.ClosesAt <= _clock.GetUtcNow().UtcDateTime))
                return Error<AdmissionIntakeFormDto>("Admission opening and closing dates must be valid and in the future.", 409);
            form.State = to; form.UpdatedAt = _clock.GetUtcNow().UtcDateTime; form.UpdatedBy = _user.UserId;
            await _uow.SaveChangesAsync(ct);
            var fields = await _fields.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant &&
                x.AdmissionIntakeFormId == id && x.IsActive).OrderBy(x => x.DisplayOrder).ToListAsync(ct);
            return ApiResponse<AdmissionIntakeFormDto>.SuccessResponse(MapForm(form, fields.Select(MapField).ToArray()),
                to == AdmissionFormState.Published ? "Admission form published." : "Admission form closed.");
        });
    }

    public async Task<ApiResponse<IReadOnlyList<AdmissionApplicantDocumentDto>>> GetDocumentsAsync(Guid applicantReference,
        CancellationToken ct = default)
    {
        if (!CanManage()) return Denied<IReadOnlyList<AdmissionApplicantDocumentDto>>();
        var tenant = _user.TenantId;
        var applicant = await _applicants.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
            x.TenantId == tenant && x.PublicId == applicantReference, ct);
        if (applicant == null) return Error<IReadOnlyList<AdmissionApplicantDocumentDto>>("Applicant not found.", 404);
        var docs = await _documents.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant &&
            x.AdmissionApplicantId == applicant.Id).OrderBy(x => x.DocumentTypeCode)
            .ThenByDescending(x => x.VersionNo).ToListAsync(ct);
        var fileIds = docs.Select(x => x.FileAssetId).Distinct().ToArray();
        var assets = await _fileAssets.GetQueryable().AsNoTracking().Where(x => x.TenantId == tenant &&
            fileIds.Contains(x.Id)).ToDictionaryAsync(x => x.Id, ct);
        IReadOnlyList<AdmissionApplicantDocumentDto> result = docs.Select(x =>
            MapDocument(x, assets.GetValueOrDefault(x.FileAssetId))).ToList();
        return ApiResponse<IReadOnlyList<AdmissionApplicantDocumentDto>>.SuccessResponse(result);
    }

    public Task<ApiResponse<AdmissionApplicantDocumentDto>> ReviewDocumentAsync(Guid applicantReference,
        long documentId, ReviewAdmissionDocumentDto request, CancellationToken ct = default)
    {
        if (!CanManage()) return Task.FromResult(Denied<AdmissionApplicantDocumentDto>());
        if (applicantReference == Guid.Empty || documentId <= 0 || request == null ||
            request.Status is not (AdmissionDocumentVerificationStatus.Verified or AdmissionDocumentVerificationStatus.Rejected) ||
            !TryVersion(request.RowVersion, out var version))
            return Task.FromResult(Error<AdmissionApplicantDocumentDto>("Valid document review request and row version required."));
        if (request.Status == AdmissionDocumentVerificationStatus.Rejected)
            return Task.FromResult(Error<AdmissionApplicantDocumentDto>("Rejection requires an explicit status field in the canonical document model. No rejection was recorded.", 409));
        return ExecuteWriteAsync("verify applicant document", async () =>
        {
            var tenant = _user.TenantId;
            var applicant = await _applicants.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
                x.TenantId == tenant && x.PublicId == applicantReference, ct);
            if (applicant == null) return Error<AdmissionApplicantDocumentDto>("Applicant not found.", 404);
            var doc = await _documents.GetQueryable().FirstOrDefaultAsync(x => x.TenantId == tenant &&
                x.Id == documentId && x.AdmissionApplicantId == applicant.Id, ct);
            if (doc == null) return Error<AdmissionApplicantDocumentDto>("Document not found.", 404);
            if (!VersionsMatch(doc.RowVersion, version)) return Stale<AdmissionApplicantDocumentDto>();
            var asset = await _fileAssets.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
                x.TenantId == tenant && x.Id == doc.FileAssetId, ct);
            if (asset == null || !asset.IsVerifiedSafe)
                return Error<AdmissionApplicantDocumentDto>("File is not cleared by upload security checks.", 409);
            doc.IsVerified = true; doc.VerifiedAt = _clock.GetUtcNow().UtcDateTime;
            doc.VerifiedByUserId = _user.UserId; doc.VerificationNote = Trim(request.Note);
            doc.UpdatedAt = _clock.GetUtcNow().UtcDateTime; doc.UpdatedBy = _user.UserId;
            await _uow.SaveChangesAsync(ct);
            return ApiResponse<AdmissionApplicantDocumentDto>.SuccessResponse(MapDocument(doc, asset),
                "Applicant document verified.");
        });
    }

    public async Task<ApiResponse<AdmissionDocumentContentDto>> GetDocumentContentAsync(Guid applicantReference,
        long documentId, CancellationToken ct = default)
    {
        if (!CanManage()) return Denied<AdmissionDocumentContentDto>();
        var tenant = _user.TenantId;
        var applicant = await _applicants.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
            x.TenantId == tenant && x.PublicId == applicantReference, ct);
        if (applicant == null) return Error<AdmissionDocumentContentDto>("Applicant not found.", 404);
        var doc = await _documents.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
            x.TenantId == tenant && x.Id == documentId && x.AdmissionApplicantId == applicant.Id, ct);
        if (doc == null) return Error<AdmissionDocumentContentDto>("Document not found.", 404);
        var asset = await _fileAssets.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x =>
            x.TenantId == tenant && x.Id == doc.FileAssetId, ct);
        if (asset == null || !asset.IsVerifiedSafe)
            return Error<AdmissionDocumentContentDto>("Document has not passed file security checks.", 403);
        var download = await _storage.GetPrivateFileAsync(asset.StorageKey);
        if (download == null) return Error<AdmissionDocumentContentDto>("Document content is unavailable.", 404);
        return ApiResponse<AdmissionDocumentContentDto>.SuccessResponse(new AdmissionDocumentContentDto
        {
            Content = download.Content, ContentType = asset.ContentType, FileName = asset.OriginalFileName
        });
    }

    private async Task<AcademicLevel?> ValidateReferencesAsync(AdmissionIntakeFormInputDto request, CancellationToken ct)
    {
        var tenant = _user.TenantId;
        if (!await _years.GetQueryable().AsNoTracking().AnyAsync(x => x.TenantId == tenant &&
            x.Id == request.AcademicYearId && x.IsActive, ct)) return null;
        if (request.AcademicTermId.HasValue && !await _terms.GetQueryable().AsNoTracking().AnyAsync(x =>
            x.TenantId == tenant && x.Id == request.AcademicTermId && x.AcademicYearId == request.AcademicYearId &&
            x.IsActive, ct)) return null;
        if (!await _campuses.GetQueryable().AsNoTracking().AnyAsync(x => x.TenantId == tenant &&
            x.Id == request.CampusId && x.IsActive, ct)) return null;
        return await _levels.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tenant &&
            x.Id == request.AcademicLevelId && x.IsActive, ct);
    }

    private static string? ValidateInput(AdmissionIntakeFormInputDto? request)
    {
        if (request == null) return "Admission form is required.";
        var error = AdmissionIntakeRules.ValidateForm(request);
        if (error != null) return error;
        if (!string.IsNullOrWhiteSpace(request.Description))
            return "Description is not supported by the canonical admission form model.";
        if (request.DocumentRequirements.Count > 0)
            return "Document requirements require a dedicated persisted policy; none were saved. Configure requirements in the supported document module.";
        return null;
    }

    private AdmissionFormField BuildField(long formId, AdmissionFormFieldDto input, DateTime now)
    {
        var row = new AdmissionFormField
        {
            TenantId = _user.TenantId, AdmissionIntakeFormId = formId,
            CreatedAt = now, CreatedBy = _user.UserId
        };
        ApplyField(row, input);
        return row;
    }
    private static void ApplyField(AdmissionFormField row, AdmissionFormFieldDto field)
    {
        row.FieldKey = field.FieldKey.Trim();
        row.Label = field.Label.Trim();
        row.DataType = field.DataType; row.IsRequired = field.IsRequired;
        row.DisplayOrder = field.DisplayOrder; row.OptionsJson = field.OptionsJson;
        row.ValidationJson = field.ValidationJson; row.IsActive = field.IsActive;
    }

    private static AdmissionIntakeFormDto MapForm(AdmissionIntakeForm form, IReadOnlyList<AdmissionFormFieldDto> fields) => new()
    {
        Id = form.Id, Reference = form.PublicId, Code = form.Code, Title = form.Title,
        CampusId = form.CampusId, AcademicYearId = form.AcademicYearId,
        AcademicTermId = form.AcademicTermId,
        AcademicProgramId = form.AcademicProgramId, AcademicLevelId = form.AcademicLevelId,
        VersionNo = form.VersionNo, State = form.State, OpensAt = form.OpensAt, ClosesAt = form.ClosesAt,
        ApplicationFee = form.ApplicationFee, CurrencyCode = form.CurrencyCode, Fields = fields,
        RowVersion = Convert.ToBase64String(form.RowVersion)
    };
    private static AdmissionFormFieldDto MapField(AdmissionFormField field) => new()
    {
        Id = field.Id, FieldKey = field.FieldKey, Label = field.Label,
        DataType = field.DataType, IsRequired = field.IsRequired, DisplayOrder = field.DisplayOrder,
        OptionsJson = field.OptionsJson, ValidationJson = field.ValidationJson, IsActive = field.IsActive,
        RowVersion = Convert.ToBase64String(field.RowVersion)
    };
    internal static AdmissionApplicantDocumentDto MapDocument(AdmissionApplicantDocument doc) => MapDocument(doc, null);
    internal static AdmissionApplicantDocumentDto MapDocument(AdmissionApplicantDocument doc, FileAsset? asset) => new()
    {
        Id = doc.Id, FileAssetId = doc.FileAssetId, DocumentTypeCode = doc.DocumentTypeCode,
        VersionNo = doc.VersionNo, IsVerified = doc.IsVerified, VerifiedByUserId = doc.VerifiedByUserId,
        VerifiedAt = doc.VerifiedAt, VerificationNote = doc.VerificationNote
    };

    private async Task<ApiResponse<T>> ExecuteWriteAsync<T>(string operation, Func<Task<ApiResponse<T>>> action)
    {
        try
        {
            using var scope = new TransactionScope(TransactionScopeOption.Required,
                new TransactionOptions { IsolationLevel = IsolationLevel.Serializable },
                TransactionScopeAsyncFlowOption.Enabled);
            var result = await action();
            if (result.Success) scope.Complete();
            return result;
        }
        catch (DbUpdateConcurrencyException ex)
        {
            _logger.LogWarning(ex, "Concurrent {Operation} for tenant {TenantId}", operation, _user.TenantId);
            return Stale<T>();
        }
        catch (DbUpdateException ex)
        {
            _logger.LogWarning(ex, "Integrity conflict in {Operation} for tenant {TenantId}", operation, _user.TenantId);
            return Error<T>("Admission data conflicts with another update.", 409);
        }
        catch (TransactionAbortedException ex)
        {
            _logger.LogWarning(ex, "Transaction aborted in {Operation} for tenant {TenantId}", operation, _user.TenantId);
            return Error<T>("Admission update conflicted with another request.", 409);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed {Operation} for tenant {TenantId}", operation, _user.TenantId);
            return Error<T>("Admission request could not be completed.", 500);
        }
    }
    private bool CanManage() => _user.IsAuthenticated && _user.TenantId > 0 &&
        (_user.IsTenantAdmin || _user.IsInRole("AdmissionOfficer"));
    private static string? Trim(string? text) => string.IsNullOrWhiteSpace(text) ? null : text.Trim();
    private static bool TryVersion(string? value, out byte[] version)
    {
        version = Array.Empty<byte>();
        if (string.IsNullOrWhiteSpace(value)) return false;
        try { version = Convert.FromBase64String(value); return version.Length > 0; }
        catch (FormatException) { return false; }
    }
    private static bool VersionsMatch(byte[] stored, byte[] expected) =>
        stored.Length == expected.Length && CryptographicOperations.FixedTimeEquals(stored, expected);
    private static ApiResponse<T> Created<T>(T value, string message) => new()
    { Success = true, StatusCode = 201, Message = message, Data = value };
    private static ApiResponse<T> Error<T>(string message, int status = 400) =>
        ApiResponse<T>.ErrorResponse(message, status);
    private static ApiResponse<T> Stale<T>() => Error<T>("Admission data changed. Reload and try again.", 409);
    private static ApiResponse<T> Denied<T>() => Error<T>("Admission officer access is required.", 403);
}
