using EduOS.Core.Common;
using EduOS.Core.DTOs.LMS;
using EduOS.Core.Entities.Academic;
using EduOS.Core.Entities.Employees;
using EduOS.Core.Entities.LMS;
using EduOS.Core.Entities.Students;
using EduOS.Core.Interfaces;
using EduOS.Core.Interfaces.IRepositories;
using EduOS.Core.Interfaces.IServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EduOS.Service.Services.LMS;

public sealed class LmsWorkflowService : ILmsWorkflowService
{
    private readonly IGenericRepository<Course> _courses; private readonly IGenericRepository<Lesson> _lessons;
    private readonly IGenericRepository<Assignment> _assignments; private readonly IGenericRepository<AssignmentSubmission> _submissions;
    private readonly IGenericRepository<CourseEnrollment> _courseEnrollments; private readonly IGenericRepository<LessonProgress> _progress;
    private readonly IGenericRepository<Enrollment> _academicEnrollments; private readonly IGenericRepository<Student> _students;
    private readonly IGenericRepository<Employee> _employees; private readonly IGenericRepository<AcademicYear> _years;
    private readonly IGenericRepository<Class> _classes; private readonly IGenericRepository<Section> _sections; private readonly IGenericRepository<Subject> _subjects;
    private readonly IUnitOfWork _unitOfWork; private readonly ICurrentUserService _currentUser; private readonly TimeProvider _clock; private readonly ILogger<LmsWorkflowService> _logger;
    public LmsWorkflowService(IGenericRepository<Course> courses, IGenericRepository<Lesson> lessons, IGenericRepository<Assignment> assignments,
        IGenericRepository<AssignmentSubmission> submissions, IGenericRepository<CourseEnrollment> courseEnrollments, IGenericRepository<LessonProgress> progress,
        IGenericRepository<Enrollment> academicEnrollments, IGenericRepository<Student> students, IGenericRepository<Employee> employees,
        IGenericRepository<AcademicYear> years, IGenericRepository<Class> classes, IGenericRepository<Section> sections, IGenericRepository<Subject> subjects,
        IUnitOfWork unitOfWork, ICurrentUserService currentUser, TimeProvider clock, ILogger<LmsWorkflowService> logger)
    { _courses=courses; _lessons=lessons; _assignments=assignments; _submissions=submissions; _courseEnrollments=courseEnrollments; _progress=progress; _academicEnrollments=academicEnrollments; _students=students; _employees=employees; _years=years; _classes=classes; _sections=sections; _subjects=subjects; _unitOfWork=unitOfWork; _currentUser=currentUser; _clock=clock; _logger=logger; }

    public async Task<ApiResponse<LmsCourseDto>> SaveCourseAsync(SaveCourseDto r, CancellationToken ct=default)
    {
        if(!CanTeach()) return ApiResponse<LmsCourseDto>.ErrorResponse("LMS authoring access is required.",403);
        var t=_currentUser.TenantId; var teacher=await ResolveTeacherAsync(r.TeacherId,ct); if(teacher==null) return ApiResponse<LmsCourseDto>.ErrorResponse("Teacher is unavailable.",409);
        if(!await _years.AnyAsync(x=>x.TenantId==t&&x.Id==r.AcademicYearId&&x.IsActive)||!await _classes.AnyAsync(x=>x.TenantId==t&&x.Id==r.ClassId&&x.IsActive)||!await _subjects.AnyAsync(x=>x.TenantId==t&&x.Id==r.SubjectId&&x.IsActive&&x.ClassId==r.ClassId)) return ApiResponse<LmsCourseDto>.ErrorResponse("Academic course references are unavailable.",409);
        if(r.SectionId.HasValue&&!await _sections.AnyAsync(x=>x.TenantId==t&&x.Id==r.SectionId.Value&&x.ClassId==r.ClassId&&x.IsActive)) return ApiResponse<LmsCourseDto>.ErrorResponse("Section is unavailable.",409);
        Course? c=null; if(r.Reference.HasValue) c=await _courses.GetQueryable().FirstOrDefaultAsync(x=>x.TenantId==t&&x.PublicId==r.Reference.Value,ct);
        if(c==null){ c=new Course{TenantId=t,PublicId=Guid.NewGuid(),CreatedAt=_clock.GetUtcNow().UtcDateTime,CreatedBy=_currentUser.UserId}; await _courses.AddAsync(c); }
        else if(!CanEditCourse(c,teacher.Id)) return ApiResponse<LmsCourseDto>.ErrorResponse("This course is owned by another teacher.",403);
        c.AcademicYearId=r.AcademicYearId;c.ClassId=r.ClassId;c.SectionId=r.SectionId;c.SubjectId=r.SubjectId;c.Title=r.Title.Trim();c.Description=Trim(r.Description);c.ThumbnailUrl=Trim(r.ThumbnailUrl);c.TeacherId=teacher.Id;c.IsActive=true;c.UpdatedAt=_clock.GetUtcNow().UtcDateTime;c.UpdatedBy=_currentUser.UserId;
        await _unitOfWork.SaveChangesAsync(ct); return ApiResponse<LmsCourseDto>.SuccessResponse(await MapCourseAsync(c,0,ct),"Course saved.");
    }
    public async Task<ApiResponse<LmsLessonDto>> SaveLessonAsync(SaveLessonDto r,CancellationToken ct=default)
    {
        var c=await GetEditableCourseAsync(r.CourseReference,ct);if(c==null)return ApiResponse<LmsLessonDto>.ErrorResponse("Course not found or not editable.",403);
        Lesson? x=null;if(r.Reference.HasValue)x=await _lessons.GetQueryable().FirstOrDefaultAsync(a=>a.TenantId==_currentUser.TenantId&&a.PublicId==r.Reference.Value&&a.CourseId==c.Id,ct);
        if(x==null){x=new Lesson{TenantId=_currentUser.TenantId,PublicId=Guid.NewGuid(),CourseId=c.Id,CreatedAt=_clock.GetUtcNow().UtcDateTime,CreatedBy=_currentUser.UserId};await _lessons.AddAsync(x);} x.Title=r.Title.Trim();x.Content=Trim(r.Content);x.VideoUrl=Trim(r.VideoUrl);x.AttachmentUrl=Trim(r.AttachmentUrl);x.OrderNo=r.OrderNo;x.Duration=r.Duration;x.UpdatedAt=_clock.GetUtcNow().UtcDateTime;x.UpdatedBy=_currentUser.UserId;await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<LmsLessonDto>.SuccessResponse(MapLesson(x,false),"Lesson saved.");
    }
    public async Task<ApiResponse<LmsAssignmentDto>> SaveAssignmentAsync(SaveAssignmentDto r,CancellationToken ct=default)
    {
        var c=await GetEditableCourseAsync(r.CourseReference,ct);if(c==null)return ApiResponse<LmsAssignmentDto>.ErrorResponse("Course not found or not editable.",403);if(r.DueDate<=_clock.GetUtcNow().UtcDateTime)return ApiResponse<LmsAssignmentDto>.ErrorResponse("Assignment due date must be in the future.");
        Assignment? x=null;if(r.Reference.HasValue)x=await _assignments.GetQueryable().FirstOrDefaultAsync(a=>a.TenantId==_currentUser.TenantId&&a.PublicId==r.Reference.Value&&a.CourseId==c.Id,ct);if(x==null){x=new Assignment{TenantId=_currentUser.TenantId,PublicId=Guid.NewGuid(),CourseId=c.Id,CreatedAt=_clock.GetUtcNow().UtcDateTime,CreatedBy=_currentUser.UserId};await _assignments.AddAsync(x);}x.Title=r.Title.Trim();x.Description=Trim(r.Description);x.TotalMark=r.TotalMark;x.DueDate=r.DueDate;x.AttachmentUrl=Trim(r.AttachmentUrl);x.IsActive=true;x.UpdatedAt=_clock.GetUtcNow().UtcDateTime;x.UpdatedBy=_currentUser.UserId;await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<LmsAssignmentDto>.SuccessResponse(MapAssignment(x,null),"Assignment saved.");
    }
    public async Task<ApiResponse<int>> EnrollClassAsync(Guid courseReference,CancellationToken ct=default)
    {
        var c=await GetEditableCourseAsync(courseReference,ct);if(c==null)return ApiResponse<int>.ErrorResponse("Course not found or not editable.",403);var t=_currentUser.TenantId;
        var q=_academicEnrollments.GetQueryable().AsNoTracking().Include(x=>x.Student).Where(x=>x.TenantId==t&&x.IsActive&&x.AcademicYearId==c.AcademicYearId&&x.ClassId==c.ClassId&&x.Student!=null&&x.Student.IsActive);if(c.SectionId.HasValue)q=q.Where(x=>x.SectionId==c.SectionId.Value);var students=await q.Select(x=>x.StudentId).Distinct().ToListAsync(ct);var existing=await _courseEnrollments.GetQueryable().Where(x=>x.TenantId==t&&x.CourseId==c.Id&&students.Contains(x.StudentId)).ToListAsync(ct);var set=existing.Select(x=>x.StudentId).ToHashSet();var now=_clock.GetUtcNow().UtcDateTime;var added=0;foreach(var id in students.Where(x=>!set.Contains(x))){await _courseEnrollments.AddAsync(new CourseEnrollment{TenantId=t,CourseId=c.Id,StudentId=id,EnrollDate=now,IsActive=true,CreatedAt=now,CreatedBy=_currentUser.UserId});added++;}await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<int>.SuccessResponse(added,"Course enrollment synchronized.");
    }
    public async Task<ApiResponse<IReadOnlyList<LmsCourseDto>>> GetMyCoursesAsync(CancellationToken ct=default)
    {
        if(!_currentUser.IsAuthenticated||_currentUser.TenantId<=0)return ApiResponse<IReadOnlyList<LmsCourseDto>>.ErrorResponse("Authentication is required.",403);var t=_currentUser.TenantId;
        if(_currentUser.IsInRole("Student")){var s=await _students.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsActive,ct);if(s==null)return ApiResponse<IReadOnlyList<LmsCourseDto>>.SuccessResponse(Array.Empty<LmsCourseDto>());var es=await _courseEnrollments.GetQueryable().AsNoTracking().Include(x=>x.Course).ThenInclude(x=>x!.Subject).Include(x=>x.Course).ThenInclude(x=>x!.Teacher).Where(x=>x.TenantId==t&&x.StudentId==s.Id&&x.IsActive&&x.Course!=null&&x.Course.IsActive).ToListAsync(ct);return ApiResponse<IReadOnlyList<LmsCourseDto>>.SuccessResponse(es.Select(x=>MapCourse(x.Course!,x.ProgressPercentage)).ToList());}
        if(CanTeach()){var teacher=await ResolveTeacherAsync(null,ct);var q=_courses.GetQueryable().AsNoTracking().Include(x=>x.Subject).Include(x=>x.Teacher).Where(x=>x.TenantId==t&&x.IsActive);if(_currentUser.IsInRole("Teacher")&&!_currentUser.IsTenantAdmin&&!_currentUser.IsInRole("Principal")){if(teacher==null)return ApiResponse<IReadOnlyList<LmsCourseDto>>.SuccessResponse(Array.Empty<LmsCourseDto>());q=q.Where(x=>x.TeacherId==teacher.Id);}var list=await q.OrderBy(x=>x.Title).ToListAsync(ct);return ApiResponse<IReadOnlyList<LmsCourseDto>>.SuccessResponse(list.Select(x=>MapCourse(x,0)).ToList());}return ApiResponse<IReadOnlyList<LmsCourseDto>>.ErrorResponse("LMS access is required.",403);
    }
    public async Task<ApiResponse<LmsCourseDetailsDto>> GetCourseAsync(Guid reference,CancellationToken ct=default)
    {
        var t=_currentUser.TenantId;var c=await _courses.GetQueryable().AsNoTracking().Include(x=>x.Subject).Include(x=>x.Teacher).FirstOrDefaultAsync(x=>x.TenantId==t&&x.PublicId==reference&&x.IsActive,ct);if(c==null)return ApiResponse<LmsCourseDetailsDto>.ErrorResponse("Course not found.",404);long? studentId=null;CourseEnrollment? ce=null;if(_currentUser.IsInRole("Student")){var s=await _students.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsActive,ct);if(s==null)return ApiResponse<LmsCourseDetailsDto>.ErrorResponse("Student profile not found.",403);studentId=s.Id;ce=await _courseEnrollments.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.CourseId==c.Id&&x.StudentId==s.Id&&x.IsActive,ct);if(ce==null)return ApiResponse<LmsCourseDetailsDto>.ErrorResponse("Student is not enrolled in this course.",403);}else if(!CanTeach())return ApiResponse<LmsCourseDetailsDto>.ErrorResponse("LMS access is required.",403);
        var lessons=await _lessons.GetQueryable().AsNoTracking().Where(x=>x.TenantId==t&&x.CourseId==c.Id).OrderBy(x=>x.OrderNo).ToListAsync(ct);var assigns=await _assignments.GetQueryable().AsNoTracking().Where(x=>x.TenantId==t&&x.CourseId==c.Id&&x.IsActive).OrderBy(x=>x.DueDate).ToListAsync(ct);var completed=studentId.HasValue?await _progress.GetQueryable().AsNoTracking().Where(x=>x.TenantId==t&&x.StudentId==studentId.Value&&x.IsCompleted&&lessons.Select(l=>l.Id).Contains(x.LessonId)).Select(x=>x.LessonId).ToListAsync(ct):new List<long>();var subs=studentId.HasValue?await _submissions.GetQueryable().AsNoTracking().Where(x=>x.TenantId==t&&x.StudentId==studentId.Value&&assigns.Select(a=>a.Id).Contains(x.AssignmentId)).ToListAsync(ct):new List<AssignmentSubmission>();var byA=subs.GroupBy(x=>x.AssignmentId).ToDictionary(x=>x.Key,x=>x.First());return ApiResponse<LmsCourseDetailsDto>.SuccessResponse(new LmsCourseDetailsDto{Course=MapCourse(c,ce?.ProgressPercentage??0),Lessons=lessons.Select(x=>MapLesson(x,completed.Contains(x.Id))).ToList(),Assignments=assigns.Select(x=>{byA.TryGetValue(x.Id,out var s);return MapAssignment(x,s);}).ToList()});
    }
    public async Task<ApiResponse<LmsAssignmentDto>> SubmitAssignmentAsync(SubmitAssignmentDto r,CancellationToken ct=default)
    {
        if(!_currentUser.IsInRole("Student")||r.ClientRequestId==Guid.Empty)return ApiResponse<LmsAssignmentDto>.ErrorResponse("Student assignment access is required.",403);if(string.IsNullOrWhiteSpace(r.SubmissionFile)&&string.IsNullOrWhiteSpace(r.SubmissionText))return ApiResponse<LmsAssignmentDto>.ErrorResponse("Submission content or file is required.");var t=_currentUser.TenantId;var s=await _students.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsActive,ct);if(s==null)return ApiResponse<LmsAssignmentDto>.ErrorResponse("Student profile not found.",403);var a=await _assignments.GetQueryable().Include(x=>x.Course).FirstOrDefaultAsync(x=>x.TenantId==t&&x.PublicId==r.AssignmentReference&&x.IsActive,ct);if(a?.Course==null)return ApiResponse<LmsAssignmentDto>.ErrorResponse("Assignment not found.",404);if(!await _courseEnrollments.AnyAsync(x=>x.TenantId==t&&x.CourseId==a.CourseId&&x.StudentId==s.Id&&x.IsActive))return ApiResponse<LmsAssignmentDto>.ErrorResponse("Student is not enrolled in this course.",403);var existing=await _submissions.GetQueryable().FirstOrDefaultAsync(x=>x.TenantId==t&&x.AssignmentId==a.Id&&x.StudentId==s.Id,ct);if(existing!=null&&existing.Status=="Reviewed")return ApiResponse<LmsAssignmentDto>.ErrorResponse("Reviewed submission cannot be changed.",409);var now=_clock.GetUtcNow().UtcDateTime;if(existing==null){existing=new AssignmentSubmission{TenantId=t,PublicId=Guid.NewGuid(),ClientRequestId=r.ClientRequestId,AssignmentId=a.Id,StudentId=s.Id,CreatedAt=now,CreatedBy=_currentUser.UserId};await _submissions.AddAsync(existing);}else if(existing.ClientRequestId!=r.ClientRequestId){existing.ClientRequestId=r.ClientRequestId;}existing.SubmissionFile=Trim(r.SubmissionFile);existing.SubmissionText=Trim(r.SubmissionText);existing.SubmittedAt=now;existing.Status=now>a.DueDate?"Late":"Submitted";existing.UpdatedAt=now;existing.UpdatedBy=_currentUser.UserId;await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<LmsAssignmentDto>.SuccessResponse(MapAssignment(a,existing),"Assignment submitted.");
    }
    public async Task<ApiResponse<bool>> ReviewSubmissionAsync(ReviewSubmissionDto r,CancellationToken ct=default)
    {
        if(!CanTeach())return ApiResponse<bool>.ErrorResponse("LMS review access is required.",403);var x=await _submissions.GetQueryable().Include(s=>s.Assignment).ThenInclude(a=>a!.Course).FirstOrDefaultAsync(s=>s.TenantId==_currentUser.TenantId&&s.PublicId==r.SubmissionReference,ct);if(x?.Assignment?.Course==null)return ApiResponse<bool>.ErrorResponse("Submission not found.",404);var teacher=await ResolveTeacherAsync(null,ct);if(!CanEditCourse(x.Assignment.Course,teacher?.Id??0))return ApiResponse<bool>.ErrorResponse("Submission belongs to another teacher.",403);if(r.Mark>x.Assignment.TotalMark)return ApiResponse<bool>.ErrorResponse("Mark cannot exceed assignment total mark.");x.Mark=r.Mark;x.Feedback=Trim(r.Feedback);x.Status="Reviewed";x.ReviewedAtUtc=_clock.GetUtcNow().UtcDateTime;x.ReviewedByUserId=_currentUser.UserId;x.UpdatedAt=x.ReviewedAtUtc;x.UpdatedBy=_currentUser.UserId;await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<bool>.SuccessResponse(true,"Submission reviewed.");
    }
    public async Task<ApiResponse<decimal>> CompleteLessonAsync(CompleteLessonDto r,CancellationToken ct=default)
    {
        if(!_currentUser.IsInRole("Student"))return ApiResponse<decimal>.ErrorResponse("Student lesson access is required.",403);var t=_currentUser.TenantId;var s=await _students.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsActive,ct);if(s==null)return ApiResponse<decimal>.ErrorResponse("Student profile not found.",403);var l=await _lessons.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.PublicId==r.LessonReference,ct);if(l==null)return ApiResponse<decimal>.ErrorResponse("Lesson not found.",404);var ce=await _courseEnrollments.GetQueryable().FirstOrDefaultAsync(x=>x.TenantId==t&&x.CourseId==l.CourseId&&x.StudentId==s.Id&&x.IsActive,ct);if(ce==null)return ApiResponse<decimal>.ErrorResponse("Student is not enrolled in this course.",403);var p=await _progress.GetQueryable().FirstOrDefaultAsync(x=>x.TenantId==t&&x.CourseEnrollmentId==ce.Id&&x.LessonId==l.Id&&x.StudentId==s.Id,ct);var now=_clock.GetUtcNow().UtcDateTime;if(p==null){p=new LessonProgress{TenantId=t,CourseEnrollmentId=ce.Id,LessonId=l.Id,StudentId=s.Id,CreatedAt=now,CreatedBy=_currentUser.UserId};await _progress.AddAsync(p);}p.IsCompleted=true;p.CompletedAtUtc=now;p.UpdatedAt=now;p.UpdatedBy=_currentUser.UserId;await _unitOfWork.SaveChangesAsync(ct);var total=await _lessons.CountAsync(x=>x.TenantId==t&&x.CourseId==l.CourseId);var done=await _progress.CountAsync(x=>x.TenantId==t&&x.CourseEnrollmentId==ce.Id&&x.IsCompleted);ce.ProgressPercentage=total==0?0m:Math.Round((decimal)done/total*100m,2);if(ce.ProgressPercentage>=100m)ce.CompletedAtUtc=now;await _unitOfWork.SaveChangesAsync(ct);return ApiResponse<decimal>.SuccessResponse(ce.ProgressPercentage,"Lesson completed.");
    }
    private async Task<Employee?> ResolveTeacherAsync(long? requested,CancellationToken ct){var t=_currentUser.TenantId;if(_currentUser.IsInRole("Teacher")&&!_currentUser.IsTenantAdmin&&!_currentUser.IsInRole("Principal"))return await _employees.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsTeacher&&x.IsActive,ct);if(requested.HasValue)return await _employees.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.Id==requested.Value&&x.IsTeacher&&x.IsActive,ct);return await _employees.GetQueryable().AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==t&&x.UserId==_currentUser.UserId&&x.IsTeacher&&x.IsActive,ct);}
    private async Task<Course?> GetEditableCourseAsync(Guid reference,CancellationToken ct){if(!CanTeach())return null;var c=await _courses.GetQueryable().FirstOrDefaultAsync(x=>x.TenantId==_currentUser.TenantId&&x.PublicId==reference&&x.IsActive,ct);if(c==null)return null;var teacher=await ResolveTeacherAsync(null,ct);return CanEditCourse(c,teacher?.Id??0)?c:null;}
    private bool CanEditCourse(Course c,long teacherId)=>_currentUser.IsTenantAdmin||_currentUser.IsInRole("Principal")||(_currentUser.IsInRole("Teacher")&&c.TeacherId==teacherId);
    private bool CanTeach()=>_currentUser.IsAuthenticated&&_currentUser.TenantId>0&&(_currentUser.IsTenantAdmin||_currentUser.IsInRole("Principal")||_currentUser.IsInRole("Teacher"));
    private async Task<LmsCourseDto> MapCourseAsync(Course c,decimal progress,CancellationToken ct){var x=await _courses.GetQueryable().AsNoTracking().Include(a=>a.Subject).Include(a=>a.Teacher).FirstAsync(a=>a.Id==c.Id,ct);return MapCourse(x,progress);} private static LmsCourseDto MapCourse(Course x,decimal progress)=>new(){Reference=x.PublicId,Title=x.Title,AcademicYearId=x.AcademicYearId,ClassId=x.ClassId,SectionId=x.SectionId,SubjectId=x.SubjectId,SubjectName=x.Subject?.Name??string.Empty,TeacherId=x.TeacherId,TeacherName=x.Teacher?.FullName??string.Empty,ProgressPercentage=progress};
    private static LmsLessonDto MapLesson(Lesson x,bool complete)=>new(){Reference=x.PublicId,Title=x.Title,Content=x.Content,VideoUrl=x.VideoUrl,AttachmentUrl=x.AttachmentUrl,OrderNo=x.OrderNo,Duration=x.Duration,IsCompleted=complete};
    private static LmsAssignmentDto MapAssignment(Assignment a,AssignmentSubmission? s)=>new(){Reference=a.PublicId,Title=a.Title,Description=a.Description,TotalMark=a.TotalMark,DueDate=a.DueDate,AttachmentUrl=a.AttachmentUrl,SubmissionReference=s?.PublicId,SubmissionStatus=s?.Status,Mark=s?.Mark,Feedback=s?.Feedback};
    private static string? Trim(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
}
