using EduOS.Core.Entities.Common;

namespace EduOS.Core.Entities.SaaS
{
    public class BillingInvoice : TenantEntity
    {
        public string InvoiceNo { get; set; } = string.Empty;

        public int? TenantSubscriptionId { get; set; }
        public TenantSubscription? TenantSubscription { get; set; }

        public DateTime BillingPeriodStart { get; set; }
        public DateTime BillingPeriodEnd { get; set; }

        public int ActiveStudentCount { get; set; }

        public decimal FixedAmount { get; set; }
        public decimal PerStudentAmount { get; set; }
        public decimal StudentChargeAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal TotalAmount { get; set; }

        public decimal PaidAmount { get; set; }
        public decimal DueAmount { get; set; }

        public DateTime IssueDate { get; set; } = DateTime.UtcNow;
        public DateTime? DueDate { get; set; }

        public string Status { get; set; } = "Pending";
        // Pending / Partial / Paid / Cancelled / Overdue

        public string? Notes { get; set; }
        public bool IsAutoGenerated { get; set; } = true;
    }
}