using EduOS.Persistence.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace EduOS.Persistence.Migrations;
[DbContext(typeof(EduOSDbContext))][Migration("20260912120000_AddLmsDeliveryWorkflow")]
public partial class AddLmsDeliveryWorkflow:Migration
{
 protected override void Up(MigrationBuilder m)
 {
  N(m,"Courses","TeacherId","Employees");N(m,"Lessons","CourseId","Courses");N(m,"Assignments","CourseId","Courses");N(m,"AssignmentSubmissions","AssignmentId","Assignments");N(m,"AssignmentSubmissions","StudentId","Students");
  ifTable(m,"CourseEnrollments","CourseId","Courses");ifTable(m,"CourseEnrollments","StudentId","Students");
  m.AddColumn<Guid>("PublicId","Courses","uniqueidentifier",nullable:false,defaultValueSql:"NEWID()");m.AddColumn<int>("AcademicYearId","Courses","int",nullable:false,defaultValue:0);m.AddColumn<int>("SectionId","Courses","int",nullable:true);
  m.AddColumn<Guid>("PublicId","Lessons","uniqueidentifier",nullable:false,defaultValueSql:"NEWID()");m.AddColumn<Guid>("PublicId","Assignments","uniqueidentifier",nullable:false,defaultValueSql:"NEWID()");
  m.AddColumn<Guid>("PublicId","AssignmentSubmissions","uniqueidentifier",nullable:false,defaultValueSql:"NEWID()");m.AddColumn<Guid>("ClientRequestId","AssignmentSubmissions","uniqueidentifier",nullable:false,defaultValueSql:"NEWID()");m.AddColumn<DateTime>("ReviewedAtUtc","AssignmentSubmissions","datetime2",nullable:true);m.AddColumn<long>("ReviewedByUserId","AssignmentSubmissions","bigint",nullable:true);
  m.Sql("UPDATE c SET AcademicYearId=ISNULL((SELECT TOP 1 AcademicYearId FROM Students s WHERE s.TenantId=c.TenantId AND s.ClassId=c.ClassId ORDER BY s.Id DESC),0) FROM Courses c WHERE c.AcademicYearId=0;");
  m.Sql("IF OBJECT_ID(N'[dbo].[CourseEnrollments]',N'U') IS NULL CREATE TABLE [dbo].[CourseEnrollments]([Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,[CourseId] bigint NOT NULL,[StudentId] bigint NOT NULL,[EnrollDate] datetime2 NOT NULL,[IsActive] bit NOT NULL,[ProgressPercentage] decimal(7,2) NOT NULL CONSTRAINT DF_CourseEnrollments_Progress DEFAULT 0,[CompletedAtUtc] datetime2 NULL,[TenantId] bigint NOT NULL,[CreatedAt] datetime2 NOT NULL,[UpdatedAt] datetime2 NULL,[CreatedBy] bigint NULL,[UpdatedBy] bigint NULL,[IsDeleted] bit NOT NULL CONSTRAINT DF_CourseEnrollments_IsDeleted DEFAULT 0,CONSTRAINT FK_CourseEnrollments_Courses_CourseId FOREIGN KEY(CourseId) REFERENCES Courses(Id),CONSTRAINT FK_CourseEnrollments_Students_StudentId FOREIGN KEY(StudentId) REFERENCES Students(Id),CONSTRAINT FK_CourseEnrollments_Tenants_TenantId FOREIGN KEY(TenantId) REFERENCES Tenants(Id));");
  m.Sql("IF COL_LENGTH('dbo.CourseEnrollments','ProgressPercentage') IS NULL ALTER TABLE CourseEnrollments ADD ProgressPercentage decimal(7,2) NOT NULL CONSTRAINT DF_CourseEnrollments_Progress2 DEFAULT 0; IF COL_LENGTH('dbo.CourseEnrollments','CompletedAtUtc') IS NULL ALTER TABLE CourseEnrollments ADD CompletedAtUtc datetime2 NULL;");
  m.CreateTable("LessonProgresses",t=>new{Id=t.Column<long>("bigint",nullable:false).Annotation("SqlServer:Identity","1, 1"),CourseEnrollmentId=t.Column<long>("bigint",nullable:false),LessonId=t.Column<long>("bigint",nullable:false),StudentId=t.Column<long>("bigint",nullable:false),IsCompleted=t.Column<bool>("bit",nullable:false),CompletedAtUtc=t.Column<DateTime>("datetime2",nullable:true),TenantId=t.Column<long>("bigint",nullable:false),CreatedAt=t.Column<DateTime>("datetime2",nullable:false),UpdatedAt=t.Column<DateTime>("datetime2",nullable:true),CreatedBy=t.Column<long>("bigint",nullable:true),UpdatedBy=t.Column<long>("bigint",nullable:true),IsDeleted=t.Column<bool>("bit",nullable:false)},c=>{c.PrimaryKey("PK_LessonProgresses",x=>x.Id);c.ForeignKey("FK_LessonProgresses_CourseEnrollments_CourseEnrollmentId",x=>x.CourseEnrollmentId,"CourseEnrollments","Id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_LessonProgresses_Lessons_LessonId",x=>x.LessonId,"Lessons","Id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_LessonProgresses_Students_StudentId",x=>x.StudentId,"Students","Id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_LessonProgresses_Tenants_TenantId",x=>x.TenantId,"Tenants","Id",onDelete:ReferentialAction.Restrict);});
  m.CreateIndex("UX_Courses_Tenant_PublicId","Courses",new[]{"TenantId","PublicId"},unique:true);m.CreateIndex("UX_Lessons_Tenant_PublicId","Lessons",new[]{"TenantId","PublicId"},unique:true);m.CreateIndex("UX_Assignments_Tenant_PublicId","Assignments",new[]{"TenantId","PublicId"},unique:true);m.CreateIndex("UX_AssignmentSubmissions_Tenant_PublicId","AssignmentSubmissions",new[]{"TenantId","PublicId"},unique:true);
  m.CreateIndex("UX_AssignmentSubmissions_Tenant_Assignment_Student","AssignmentSubmissions",new[]{"TenantId","AssignmentId","StudentId"},unique:true,filter:"[IsDeleted] = 0");m.CreateIndex("UX_CourseEnrollments_Tenant_Course_Student","CourseEnrollments",new[]{"TenantId","CourseId","StudentId"},unique:true,filter:"[IsDeleted] = 0");m.CreateIndex("IX_LessonProgresses_CourseEnrollmentId","LessonProgresses","CourseEnrollmentId");m.CreateIndex("IX_LessonProgresses_LessonId","LessonProgresses","LessonId");m.CreateIndex("IX_LessonProgresses_StudentId","LessonProgresses","StudentId");m.CreateIndex("IX_LessonProgresses_TenantId","LessonProgresses","TenantId");m.CreateIndex("UX_LessonProgresses_Tenant_Enrollment_Lesson","LessonProgresses",new[]{"TenantId","CourseEnrollmentId","LessonId"},unique:true,filter:"[IsDeleted] = 0");
 }
 protected override void Down(MigrationBuilder m){m.DropTable("LessonProgresses");}
 private static void N(MigrationBuilder m,string table,string col,string principal)=>m.Sql($@"DECLARE @s nvarchar(max)=N'';SELECT @s+=N'ALTER TABLE [dbo].[{table}] DROP CONSTRAINT ['+fk.name+N'];' FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fk.object_id=fkc.constraint_object_id JOIN sys.columns c ON c.object_id=fkc.parent_object_id AND c.column_id=fkc.parent_column_id WHERE fkc.parent_object_id=OBJECT_ID(N'[dbo].[{table}]') AND c.name=N'{col}';IF LEN(@s)>0 EXEC sp_executesql @s;DECLARE @i nvarchar(max)=N'';SELECT @i+=N'DROP INDEX ['+i.name+N'] ON [dbo].[{table}];' FROM sys.indexes i JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE i.object_id=OBJECT_ID(N'[dbo].[{table}]') AND c.name=N'{col}' AND i.is_primary_key=0 AND i.is_unique_constraint=0;IF LEN(@i)>0 EXEC sp_executesql @i;ALTER TABLE [dbo].[{table}] ALTER COLUMN [{col}] bigint NOT NULL;CREATE INDEX [IX_{table}_{col}] ON [dbo].[{table}]([{col}]);ALTER TABLE [dbo].[{table}] WITH CHECK ADD CONSTRAINT [FK_{table}_{principal}_{col}] FOREIGN KEY([{col}]) REFERENCES [dbo].[{principal}]([Id]);");
 private static void ifTable(MigrationBuilder m,string table,string col,string principal)=>m.Sql($@"IF OBJECT_ID(N'[dbo].[{table}]',N'U') IS NOT NULL BEGIN DECLARE @s nvarchar(max)=N'';SELECT @s+=N'ALTER TABLE [dbo].[{table}] DROP CONSTRAINT ['+fk.name+N'];' FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fk.object_id=fkc.constraint_object_id JOIN sys.columns c ON c.object_id=fkc.parent_object_id AND c.column_id=fkc.parent_column_id WHERE fkc.parent_object_id=OBJECT_ID(N'[dbo].[{table}]') AND c.name=N'{col}';IF LEN(@s)>0 EXEC sp_executesql @s;ALTER TABLE [dbo].[{table}] ALTER COLUMN [{col}] bigint NOT NULL;END");
}
